{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-yaml",
    "version": "2.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.17.0.jar",
          "url": "jackson-dataformat-yaml-2.17.0.jar",
          "size": 54270,
          "sha512": "8eac6846dea590a35d1f23443db15198eb2b3bb927caa597ffdc242853a8d89a105e9740b99f870ee4bfd20991184d99f6f10b3398c9cc6a975d50d9a490ee94",
          "sha256": "effe59787e84e552f2e5316f7bf0893add3ba5fa2032f28c5f44f99fcadf30cf",
          "sha1": "d9e0f965152838e62654845c47513e05ee65c6cc",
          "md5": "87d88d7098940e89439f72d4789651b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.17.0.jar",
          "url": "jackson-dataformat-yaml-2.17.0.jar",
          "size": 54270,
          "sha512": "8eac6846dea590a35d1f23443db15198eb2b3bb927caa597ffdc242853a8d89a105e9740b99f870ee4bfd20991184d99f6f10b3398c9cc6a975d50d9a490ee94",
          "sha256": "effe59787e84e552f2e5316f7bf0893add3ba5fa2032f28c5f44f99fcadf30cf",
          "sha1": "d9e0f965152838e62654845c47513e05ee65c6cc",
          "md5": "87d88d7098940e89439f72d4789651b6"
        }
      ]
    }
  ]
}
