{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diffplug.spotless",
    "module": "spotless-lib-extra",
    "version": "2.19.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "dc7bd6pcnbf4raxw3w5f5y3lj4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-2.19.2.jar",
          "url": "spotless-lib-extra-2.19.2.jar",
          "size": 78351,
          "sha512": "7fca53bb9eb21e4e7da3a5ebd08ab8e217f22eb0a0615ae7e0b1612f29940480f1d6c84dd972ec4ba505a907faa1826323d94ed3d05bb7e9e78e16358008b1e7",
          "sha256": "609a80d5adc0c5c6a1710033a3fa9507f71cecdd8434d2ca870a64f90c35624c",
          "sha1": "410fbe11a0c422e9febc6f6407341651eb241713",
          "md5": "d0411283343790ccf3107301c4f23054"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.diffplug.durian",
          "module": "durian-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.diffplug.durian",
          "module": "durian-collect",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "5.10.0.202012080955-r"
          }
        },
        {
          "group": "com.googlecode.concurrent-trees",
          "module": "concurrent-trees",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-lib",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "spotless-lib-extra-2.19.2.jar",
          "url": "spotless-lib-extra-2.19.2.jar",
          "size": 78351,
          "sha512": "7fca53bb9eb21e4e7da3a5ebd08ab8e217f22eb0a0615ae7e0b1612f29940480f1d6c84dd972ec4ba505a907faa1826323d94ed3d05bb7e9e78e16358008b1e7",
          "sha256": "609a80d5adc0c5c6a1710033a3fa9507f71cecdd8434d2ca870a64f90c35624c",
          "sha1": "410fbe11a0c422e9febc6f6407341651eb241713",
          "md5": "d0411283343790ccf3107301c4f23054"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-2.19.2-javadoc.jar",
          "url": "spotless-lib-extra-2.19.2-javadoc.jar",
          "size": 455680,
          "sha512": "98e230fbcb07f741ce717816e7d22b85780983a91f99b6963f037137f3a9b1b1181232b1274792dd6fe01e4ef25d93abd0998c07d0750c8f27cd2e7e6e7c7326",
          "sha256": "e4c4fc08e74ee0f339639de78b4b30336938fcac5c76fcd3919047549b760334",
          "sha1": "a1c0cb9cb1d3b629e6867d8f5fd22538b2a339c9",
          "md5": "fbf7c017c924f95c1778034134e2dea1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-extra-2.19.2-sources.jar",
          "url": "spotless-lib-extra-2.19.2-sources.jar",
          "size": 58450,
          "sha512": "6e62c60bcd1a8fc3f83d82d8fe9799d3061d42969ade5ba07f3c67cfd627817d3c36bce3480cb3c9ca069cc8b7df7ab817350675a195b88f1be72ddf15b24362",
          "sha256": "c5a413720ca737fd595768745d7a1cdb31be05548b30bace1375bffd7f69b72d",
          "sha1": "971be0ac1e2734d853fd426a29bfd4fed56eacf6",
          "md5": "47cc4be61bb80f617983d718b9f134a8"
        }
      ]
    }
  ]
}
