# Server configuration
server.port=8080

# Vaadin configuration
#vaadin.launch-browser=false
vaadin.launch-browser=true
# Production mode enabled so _index.html is required on classpath
vaadin.productionMode=true
#vaadin.productionMode=false
