{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-core",
    "version": "6.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.1.9.jar",
          "url": "spring-core-6.1.9.jar",
          "size": 1882797,
          "sha512": "887a3f43cb78dd231e47596420a714668769254ddf5d71b5deaa81353900748c6059c2779ac6234cf2b3ec6504a94f021be52fb8029f8182fc3716953708e03f",
          "sha256": "7061e6174bbe19f8508fb9538b41e6daf35175468cfd13eb44a7ebddb8674fd1",
          "sha1": "e96ffbc7a286d4ce5007bb89a8dc1cdce10974da",
          "md5": "43c702c43e08016e49b8652bad0bc68b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-jcl",
          "version": {
            "requires": "6.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-6.1.9.jar",
          "url": "spring-core-6.1.9.jar",
          "size": 1882797,
          "sha512": "887a3f43cb78dd231e47596420a714668769254ddf5d71b5deaa81353900748c6059c2779ac6234cf2b3ec6504a94f021be52fb8029f8182fc3716953708e03f",
          "sha256": "7061e6174bbe19f8508fb9538b41e6daf35175468cfd13eb44a7ebddb8674fd1",
          "sha1": "e96ffbc7a286d4ce5007bb89a8dc1cdce10974da",
          "md5": "43c702c43e08016e49b8652bad0bc68b"
        }
      ]
    }
  ]
}
