{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diffplug.spotless",
    "module": "spotless-lib",
    "version": "2.19.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "dc7bd6pcnbf4raxw3w5f5y3lj4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spotless-lib-2.19.2.jar",
          "url": "spotless-lib-2.19.2.jar",
          "size": 289530,
          "sha512": "dfef5d78bd4318d6ae139de592095f9ce701403e4d3e0d75f317b106c2d1dc5caafa496c604a8335388e8b1231ea35e347f07e9a272303ae9cfe7f69967d4707",
          "sha256": "3b96abc91be4dc0db2541918a260c8b1e2c1dc790ce50a6698dec6104ae15efe",
          "sha1": "6bb7320b7afa98e97d43bf52f56e151adf971c64",
          "md5": "7730ca6600024990a008c9a157ecd6ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-2.19.2.jar",
          "url": "spotless-lib-2.19.2.jar",
          "size": 289530,
          "sha512": "dfef5d78bd4318d6ae139de592095f9ce701403e4d3e0d75f317b106c2d1dc5caafa496c604a8335388e8b1231ea35e347f07e9a272303ae9cfe7f69967d4707",
          "sha256": "3b96abc91be4dc0db2541918a260c8b1e2c1dc790ce50a6698dec6104ae15efe",
          "sha1": "6bb7320b7afa98e97d43bf52f56e151adf971c64",
          "md5": "7730ca6600024990a008c9a157ecd6ab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-2.19.2-javadoc.jar",
          "url": "spotless-lib-2.19.2-javadoc.jar",
          "size": 731774,
          "sha512": "721547708b047f6dd95fe52bef7e6a1a243e61def3f9ec377ad139ed99bad4d0853e8d0b25e2d79bbdde42191648dd42e1c4eac4cbabc376e0a0ca084d370231",
          "sha256": "2d929c6f59c127bfecd9ee92be36a9258cea03d3a645558d68b5ac8d11f58ed8",
          "sha1": "5500894c89f6e79942541468654490fd69d79a6a",
          "md5": "baffa23df1a27d578f57a7264aef03a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotless-lib-2.19.2-sources.jar",
          "url": "spotless-lib-2.19.2-sources.jar",
          "size": 152308,
          "sha512": "5525b62864cfb9e3c605f2bdc2a31c9b43df1d0c5ae38ecd2aef0245ca450c3c568e5a7cde7b30f2e1830c5fef0993a317c7f5027298cdf6e335febe30b1d5de",
          "sha256": "d450f46f560056f7ac4da650ba41edf82f0330013bd9ad0faaa36ba8e4bd0a30",
          "sha1": "b0c602adbbbf2d8dd8d16d2553870491c23389a6",
          "md5": "805b03c09fe1a6de1fb04205457797c5"
        }
      ]
    }
  ]
}
