{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-parameter-names",
    "version": "2.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.17.0.jar",
          "url": "jackson-module-parameter-names-2.17.0.jar",
          "size": 9459,
          "sha512": "d692e1be1bab4f3c3bf5709d7431ece2c8eefbe3fb87ec627cad1db3fa754bdaed7686d4db351b5946a7213ddc9af7282c64ede34cb7b8deaed30d84032533c8",
          "sha256": "23ac48352979cc8614f756b406034f21430ebed010ca6bfa6760e856b9a17173",
          "sha1": "8a14f3e5bdc2ba388d4a01af0589155e88a2b94e",
          "md5": "f01bd867faf75a623bcb2a3b16d451b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.17.0.jar",
          "url": "jackson-module-parameter-names-2.17.0.jar",
          "size": 9459,
          "sha512": "d692e1be1bab4f3c3bf5709d7431ece2c8eefbe3fb87ec627cad1db3fa754bdaed7686d4db351b5946a7213ddc9af7282c64ede34cb7b8deaed30d84032533c8",
          "sha256": "23ac48352979cc8614f756b406034f21430ebed010ca6bfa6760e856b9a17173",
          "sha1": "8a14f3e5bdc2ba388d4a01af0589155e88a2b94e",
          "md5": "f01bd867faf75a623bcb2a3b16d451b7"
        }
      ]
    }
  ]
}
