{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jdk8",
    "version": "2.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.17.0.jar",
          "url": "jackson-datatype-jdk8-2.17.0.jar",
          "size": 35142,
          "sha512": "313ccffb5ef323b51424b85587df35df0569c7ad966d1c0f80ec2fb9b1c28b26c00dd786f1b8be409687659fd7ba2495c92c1f2952aed5963bb99a6ac010fcfe",
          "sha256": "1c98cfbeaccfd1425bc6a2af7b8d396da4cd9574bbb715fc9b8324e381102a89",
          "sha1": "d3044177aeb61027e2c46512b43c853b3266d4b6",
          "md5": "f0fe5f62590bd1f0f469ea6bbafd59f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.17.0.jar",
          "url": "jackson-datatype-jdk8-2.17.0.jar",
          "size": 35142,
          "sha512": "313ccffb5ef323b51424b85587df35df0569c7ad966d1c0f80ec2fb9b1c28b26c00dd786f1b8be409687659fd7ba2495c92c1f2952aed5963bb99a6ac010fcfe",
          "sha256": "1c98cfbeaccfd1425bc6a2af7b8d396da4cd9574bbb715fc9b8324e381102a89",
          "sha1": "d3044177aeb61027e2c46512b43c853b3266d4b6",
          "md5": "f0fe5f62590bd1f0f469ea6bbafd59f"
        }
      ]
    }
  ]
}
