{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-jcl",
    "version": "6.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-jcl-6.1.9.jar",
          "url": "spring-jcl-6.1.9.jar",
          "size": 24537,
          "sha512": "6f4aa23f6b8d64639f5b039744d10409cd3a14fdcc2d2069df0f1e0fdc4e9928200e3fee682f6c529ed4ba841895f2da1c97f7c6f53384e5acb3457f7f8b4ec6",
          "sha256": "a3ff635b465bb793ddf41cac4df6094937af3417ac825fd2bb3f287261e5b236",
          "sha1": "c050772ca5ce23ab68ad14b745c63a4607bd1c0b",
          "md5": "7fdd5dea70c09244224f0a0f5940a464"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-jcl-6.1.9.jar",
          "url": "spring-jcl-6.1.9.jar",
          "size": 24537,
          "sha512": "6f4aa23f6b8d64639f5b039744d10409cd3a14fdcc2d2069df0f1e0fdc4e9928200e3fee682f6c529ed4ba841895f2da1c97f7c6f53384e5acb3457f7f8b4ec6",
          "sha256": "a3ff635b465bb793ddf41cac4df6094937af3417ac825fd2bb3f287261e5b236",
          "sha1": "c050772ca5ce23ab68ad14b745c63a4607bd1c0b",
          "md5": "7fdd5dea70c09244224f0a0f5940a464"
        }
      ]
    }
  ]
}
